import type { Metadata } from "next";
import Link from "next/link";
import { LegalLayout, type LegalSection } from "@/components/legal-layout";

export const metadata: Metadata = {
  title: "Privacy Policy · AIthlete",
  description: "How AIthlete handles your Strava data.",
};

const SECTIONS: LegalSection[] = [
  {
    title: "What we access from Strava",
    body: (
      <>
        <p>
          When you sign in with Strava we request the minimum scopes required
          to power the app:
        </p>
        <ul className="mt-3 space-y-2 list-none pl-0">
          <li className="flex gap-3">
            <span className="text-coral select-none">·</span>
            <span>
              <strong className="font-semibold text-ink-900">read</strong> ·
              your athlete profile (name, avatar, locale, weight, FTP)
            </span>
          </li>
          <li className="flex gap-3">
            <span className="text-coral select-none">·</span>
            <span>
              <strong className="font-semibold text-ink-900">
                activity:read_all
              </strong>{" "}
              · your activity list, individual activity details, and lifetime
              stats — used to compute training load, intensity, and progress
            </span>
          </li>
          <li className="flex gap-3">
            <span className="text-coral select-none">·</span>
            <span>
              <strong className="font-semibold text-ink-900">profile:read_all</strong> ·
              your heart-rate and power zones, used to map effort into the
              correct training band
            </span>
          </li>
        </ul>
        <p className="mt-4">
          We do not request write permissions. We cannot post activities,
          modify your account, or upload routes on your behalf.
        </p>
      </>
    ),
  },
  {
    title: "What we never access",
    body: (
      <>
        <p>
          We never see your Strava password, your email address from Strava,
          your private messages, your billing information, or your contacts.
          Authentication is handled by Strava&apos;s OAuth servers — your
          password is never transmitted to or stored by AIthlete.
        </p>
      </>
    ),
  },
  {
    title: "Where your data lives",
    body: (
      <>
        <p>
          AIthlete is deliberately stateless. We do not maintain a database of
          your activities, debriefs, or chat history. Each time you open a
          page, we fetch fresh data from Strava, compute metrics in memory,
          render the page, and discard the data when your session ends.
        </p>
        <p className="mt-3">
          Your Strava access token is stored inside a signed, HTTP-only session
          cookie issued to your browser. The cookie is encrypted with a server
          secret, scoped to our domain, and expires when you sign out. No
          third-party analytics or session-replay tools have access to it.
        </p>
      </>
    ),
  },
  {
    title: "AI processing",
    body: (
      <>
        <p>
          The narrative layer of the app (debriefs, weekly analysis, coach
          chat) is generated by Anthropic Claude. Before calling the model we
          strip your data down to numeric training metrics — pace, heart rate,
          power, time-in-zone, mileage, elevation. We do not send the AI your
          Strava email, your home address, or the GPS coordinates of any
          individual point in your activity stream.
        </p>
        <p className="mt-3">
          Anthropic processes these requests under its{" "}
          <a
            href="https://www.anthropic.com/legal/commercial-terms"
            target="_blank"
            rel="noreferrer noopener"
            className="text-coral underline decoration-dotted underline-offset-2"
          >
            Commercial Terms
          </a>{" "}
          and does not train its models on the data we send via the API.
        </p>
      </>
    ),
  },
  {
    title: "What we never do",
    body: (
      <ul className="space-y-2 list-none pl-0">
        <li className="flex gap-3">
          <span className="text-coral select-none">·</span>
          <span>Sell, rent, or trade your data — to anyone, ever.</span>
        </li>
        <li className="flex gap-3">
          <span className="text-coral select-none">·</span>
          <span>Use your data to train any AI model.</span>
        </li>
        <li className="flex gap-3">
          <span className="text-coral select-none">·</span>
          <span>
            Show ads, run third-party trackers, or embed pixels from ad
            networks.
          </span>
        </li>
        <li className="flex gap-3">
          <span className="text-coral select-none">·</span>
          <span>
            Share your data with other athletes, including segment leaders,
            clubs, or friends.
          </span>
        </li>
      </ul>
    ),
  },
  {
    title: "Cookies",
    body: (
      <>
        <p>
          AIthlete uses a small number of <strong className="font-semibold text-ink-900">strictly-necessary cookies</strong>{" "}
          — the kind required to log you in and keep you logged in. We do not
          set analytics cookies, advertising cookies, tracking pixels, or any
          third-party cookies.
        </p>

        <div className="mt-5 rounded-2xl border border-ink-100 bg-cream-warm overflow-hidden">
          <table className="w-full text-[12.5px] leading-snug">
            <thead className="bg-cream-deep/70 text-ink-700">
              <tr className="text-left">
                <th className="px-3.5 py-2.5 font-display font-semibold text-[11px] uppercase tracking-[0.1em]">
                  Name
                </th>
                <th className="px-3.5 py-2.5 font-display font-semibold text-[11px] uppercase tracking-[0.1em]">
                  Purpose
                </th>
                <th className="px-3.5 py-2.5 font-display font-semibold text-[11px] uppercase tracking-[0.1em] hidden sm:table-cell">
                  Lifetime
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-ink-100/70 text-ink-700">
              <tr>
                <td className="px-3.5 py-3 align-top font-mono text-[11.5px] text-coral-700">
                  authjs.session-token
                </td>
                <td className="px-3.5 py-3 align-top">
                  Encrypted JWT that keeps you signed in and carries your
                  Strava access token between pages. Without this cookie the
                  app cannot fetch any of your data.
                </td>
                <td className="px-3.5 py-3 align-top nums hidden sm:table-cell">
                  30 days
                </td>
              </tr>
              <tr>
                <td className="px-3.5 py-3 align-top font-mono text-[11.5px] text-coral-700">
                  authjs.csrf-token
                </td>
                <td className="px-3.5 py-3 align-top">
                  Cross-site request forgery token that protects the OAuth
                  callback from being triggered by another site.
                </td>
                <td className="px-3.5 py-3 align-top nums hidden sm:table-cell">
                  session
                </td>
              </tr>
              <tr>
                <td className="px-3.5 py-3 align-top font-mono text-[11.5px] text-coral-700">
                  authjs.callback-url
                </td>
                <td className="px-3.5 py-3 align-top">
                  Remembers the page you were heading to so we can return you
                  there after Strava sign-in.
                </td>
                <td className="px-3.5 py-3 align-top nums hidden sm:table-cell">
                  session
                </td>
              </tr>
              <tr>
                <td className="px-3.5 py-3 align-top font-mono text-[11.5px] text-coral-700">
                  authjs.pkce.code_verifier
                </td>
                <td className="px-3.5 py-3 align-top">
                  Short-lived PKCE challenge that secures the Strava OAuth
                  handshake. Set when sign-in starts and dropped immediately
                  after Strava redirects back.
                </td>
                <td className="px-3.5 py-3 align-top nums hidden sm:table-cell">
                  ~15 min
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="mt-4">
          All four cookies are flagged{" "}
          <code className="text-[12.5px] bg-cream-deep px-1.5 py-0.5 rounded">
            HttpOnly
          </code>
          ,{" "}
          <code className="text-[12.5px] bg-cream-deep px-1.5 py-0.5 rounded">
            Secure
          </code>{" "}
          (in production) and{" "}
          <code className="text-[12.5px] bg-cream-deep px-1.5 py-0.5 rounded">
            SameSite=Lax
          </code>
          . They are first-party only — no third party can read them.
        </p>

        <div className="mt-5 rounded-2xl border border-coral-100 bg-coral-50/60 px-4 py-3.5">
          <div className="text-[10px] uppercase tracking-[0.18em] font-semibold text-coral-700">
            Do you need to accept a cookie banner?
          </div>
          <p className="mt-2 text-[13.5px] leading-relaxed text-ink-700">
            <strong className="font-semibold text-ink-900">No.</strong>{" "}
            Under EU/UK ePrivacy rules (PECR) and similar laws elsewhere,
            consent is only required for cookies that are{" "}
            <em className="not-italic font-semibold">not</em> strictly
            necessary — analytics, advertising, profiling, fingerprinting.
            All of the cookies AIthlete sets are essential to logging you in.
            That is why you will never see a cookie pop-up on this app.
          </p>
        </div>
      </>
    ),
  },
  {
    title: "Your rights",
    body: (
      <>
        <p>
          You have the right to revoke our access to your Strava data at any
          time, from{" "}
          <a
            href="https://www.strava.com/settings/apps"
            target="_blank"
            rel="noreferrer noopener"
            className="text-coral underline decoration-dotted underline-offset-2"
          >
            strava.com/settings/apps
          </a>
          . Because we keep no server-side database, there is nothing for us to
          delete once access is revoked — the next request to Strava simply
          fails.
        </p>
        <p className="mt-3">
          If you are a resident of the EU/UK (GDPR) or California (CCPA), the
          rights you have under those laws — access, rectification, erasure,
          portability, objection — apply automatically: you exercise them by
          revoking our Strava access, since that is the only way we hold your
          data at all.
        </p>
      </>
    ),
  },
  {
    title: "Children",
    body: (
      <p>
        AIthlete is not directed at children under 13 (or under 16 where
        required by local law). We do not knowingly process data from anyone
        below those ages. If you believe a minor has signed in, contact us at
        the email below and we will help disconnect the account.
      </p>
    ),
  },
  {
    title: "Changes to this policy",
    body: (
      <p>
        If we materially change how we handle your data — for example, by
        introducing a database, persistent training history, or any new
        external processor — we will update this page and the effective date
        at the top. We encourage you to check back occasionally.
      </p>
    ),
  },
  {
    title: "Contact",
    body: (
      <p>
        Privacy questions, requests, or concerns — reach out via the{" "}
        <Link
          href="/contact"
          className="text-coral underline decoration-dotted underline-offset-2"
        >
          contact page
        </Link>{" "}
        or email{" "}
        <a
          href="mailto:ashok.kota251@gmail.com"
          className="text-coral underline decoration-dotted underline-offset-2"
        >
          ashok.kota251@gmail.com
        </a>
        .
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      eyebrow="How we handle your data"
      title="Privacy"
      effectiveDate="May 31, 2026"
      lede="AIthlete is built stateless. Your Strava data is read on demand, held in memory for the page render, and dropped when you close the tab. Here is exactly what that means."
      sections={SECTIONS}
      footer={
        <p>
          See our{" "}
          <Link
            href="/terms"
            className="text-coral underline decoration-dotted underline-offset-2"
          >
            Terms of Service
          </Link>{" "}
          for the rules that govern your use of the app. AIthlete uses the
          official Strava API; Strava&apos;s own{" "}
          <a
            href="https://www.strava.com/legal/privacy"
            target="_blank"
            rel="noreferrer noopener"
            className="text-coral underline decoration-dotted underline-offset-2"
          >
            Privacy Policy
          </a>{" "}
          covers what Strava does with your data.
        </p>
      }
    />
  );
}
