import type { Stretch } from "./types";

export const STRETCHES: Stretch[] = [
  /* ─── Lower body — calves / Achilles ──────────────────────────────── */
  {
    id: "calf-wall",
    name: "Calf wall stretch",
    targetArea: "calves",
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Targets the gastrocnemius — the upper, larger calf muscle.",
    steps: [
      "Face a wall, place both hands on it at shoulder height.",
      "Step one foot back, keep that heel pressed into the floor.",
      "Bend the front knee and lean into the wall until you feel the back calf stretch.",
      "Keep the back leg straight. Breathe.",
    ],
    sportRelevance: ["run", "ride", "any"],
  },
  {
    id: "soleus-bent-knee",
    name: "Bent-knee calf stretch",
    targetArea: "calves",
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Targets the soleus — the deeper, lower calf muscle that drives toe-off.",
    steps: [
      "Same wall position as the calf wall stretch.",
      "Step the back foot a bit closer than usual.",
      "Bend the back knee while keeping the heel down.",
      "You should feel the stretch lower in the leg, closer to the ankle.",
    ],
    sportRelevance: ["run", "any"],
  },
  {
    id: "downward-dog-pedal",
    name: "Downward-dog pedal",
    targetArea: "calves",
    secondaryAreas: ["hamstrings"],
    durationSec: 45,
    sides: 1,
    difficulty: "easy",
    description: "Pedalling the heels in down-dog loads each calf alternately.",
    steps: [
      "Start in a downward-dog (inverted-V) position, hands and feet on the floor.",
      "Bend one knee while pressing the opposite heel down.",
      "Alternate sides slowly, holding each heel-press for a breath.",
      "Continue for 45 seconds total.",
    ],
    cautions: ["Skip if you have a wrist injury."],
    sportRelevance: ["run", "any"],
  },

  /* ─── Lower body — quads ─────────────────────────────────────────── */
  {
    id: "standing-quad-pull",
    name: "Standing quad pull",
    targetArea: "quads",
    secondaryAreas: ["hipFlexors"],
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Classic quad stretch — works the rectus femoris through the hip.",
    steps: [
      "Stand near a wall for balance.",
      "Bend one knee and grab the same-side ankle behind you.",
      "Pull the heel toward your glute. Keep knees together.",
      "Squeeze the glute to deepen the stretch.",
    ],
    cautions: ["Avoid if you have knee pain when flexing the joint."],
    sportRelevance: ["run", "ride", "any"],
  },
  {
    id: "couch-stretch",
    name: "Couch stretch",
    targetArea: "quads",
    secondaryAreas: ["hipFlexors"],
    durationSec: 60,
    sides: 2,
    difficulty: "moderate",
    description: "Aggressive quad + hip-flexor stretch — common cyclist mobility work.",
    steps: [
      "Kneel facing away from a couch or wall.",
      "Place the top of your back foot up against the couch, shin vertical.",
      "Bring the front foot forward into a lunge stance.",
      "Tuck the pelvis (squeeze glute) and slowly raise your torso upright.",
    ],
    cautions: ["Go gently — this stretch is intense. Skip if knees ache."],
    sportRelevance: ["ride", "run", "any"],
  },

  /* ─── Lower body — hamstrings ─────────────────────────────────────── */
  {
    id: "standing-toe-touch",
    name: "Standing toe-touch",
    targetArea: "hamstrings",
    secondaryAreas: ["lowerBack"],
    durationSec: 30,
    sides: 1,
    difficulty: "easy",
    description: "Forward fold — releases hamstrings + decompresses the spine.",
    steps: [
      "Stand with feet hip-width.",
      "Hinge from the hips, letting your spine round forward.",
      "Let your hands hang toward the floor or grab opposite elbows.",
      "Soften the knees if your hamstrings are tight.",
    ],
    sportRelevance: ["run", "ride", "any"],
  },
  {
    id: "seated-single-leg",
    name: "Seated single-leg fold",
    targetArea: "hamstrings",
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Isolates each hamstring — useful when one side is tighter than the other.",
    steps: [
      "Sit with one leg extended straight, the other tucked in.",
      "Hinge forward from the hips toward the extended foot.",
      "Reach for the toes — don't force range, let breath open the muscle.",
      "Keep the back of the extended knee on the floor.",
    ],
    sportRelevance: ["run", "any"],
  },
  {
    id: "supine-hamstring-strap",
    name: "Reclined hamstring with strap",
    targetArea: "hamstrings",
    durationSec: 45,
    sides: 2,
    difficulty: "easy",
    description: "Low-back-friendly hamstring stretch using a towel or band.",
    steps: [
      "Lie on your back, one knee bent with foot on the floor.",
      "Loop a towel or band around the other foot.",
      "Straighten that leg upward as far as comfortable, pulling gently with the strap.",
      "Keep the working knee fully straight; flex the foot.",
    ],
    sportRelevance: ["run", "ride", "any"],
  },

  /* ─── Lower body — hip flexors / hips ────────────────────────────── */
  {
    id: "hip-flexor-lunge",
    name: "Half-kneeling hip flexor",
    targetArea: "hipFlexors",
    durationSec: 45,
    sides: 2,
    difficulty: "easy",
    description: "The most useful single stretch for cyclists and desk workers.",
    steps: [
      "Kneel on one knee, the other foot planted in front (90° at both knees).",
      "Tuck your pelvis under (squeeze the back glute).",
      "Lean forward through the hip — feel the stretch in the front of the back-leg hip.",
      "Raise the same-side arm overhead for a deeper stretch.",
    ],
    sportRelevance: ["ride", "run", "any"],
  },
  {
    id: "pigeon-pose",
    name: "Pigeon pose",
    targetArea: "glutes",
    secondaryAreas: ["hipFlexors"],
    durationSec: 60,
    sides: 2,
    difficulty: "moderate",
    description: "Deep glute and external-rotator opener — runner's gold.",
    steps: [
      "From hands and knees, slide one knee forward toward the same-side hand.",
      "Extend the other leg straight back.",
      "Square your hips down and forward.",
      "Lower onto your forearms or all the way down if comfortable.",
    ],
    cautions: ["Skip or modify if you have knee pain."],
    sportRelevance: ["run", "ride", "any"],
  },
  {
    id: "figure-4-supine",
    name: "Figure-4 (supine)",
    targetArea: "glutes",
    durationSec: 45,
    sides: 2,
    difficulty: "easy",
    description: "Pigeon's gentler cousin — easier on knees, same target.",
    steps: [
      "Lie on your back, both knees bent, feet on the floor.",
      "Cross one ankle over the opposite knee (the '4' shape).",
      "Reach through and grab the back of the planted thigh.",
      "Gently pull the leg toward your chest.",
    ],
    sportRelevance: ["run", "ride", "any"],
  },

  /* ─── Lower body — IT band ────────────────────────────────────────── */
  {
    id: "standing-it-band",
    name: "Standing IT-band cross-over",
    targetArea: "itBand",
    secondaryAreas: ["glutes"],
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Side-body opener that targets the lateral hip and IT band.",
    steps: [
      "Stand tall, cross one foot in front of the other.",
      "Raise the arm on the same side as the back foot overhead.",
      "Lean toward the front-foot side, feeling the stretch down the outer hip.",
      "Keep both feet planted.",
    ],
    sportRelevance: ["run", "any"],
  },

  /* ─── Lower body — ankles / feet ──────────────────────────────────── */
  {
    id: "ankle-circles",
    name: "Ankle circles",
    targetArea: "ankles",
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Mobility, not stretch — keeps the joint moving in all planes.",
    steps: [
      "Sit and extend one leg.",
      "Slowly trace a large circle with the foot — 5 rotations each direction.",
      "Move only the ankle, not the leg.",
      "Switch feet.",
    ],
    sportRelevance: ["run", "any"],
  },
  {
    id: "plantar-roll",
    name: "Plantar fascia ball roll",
    targetArea: "feet",
    durationSec: 60,
    sides: 2,
    difficulty: "easy",
    description: "Lacrosse / tennis ball under the arch — releases foot tension.",
    steps: [
      "Stand near something to hold for balance.",
      "Place a small ball under one bare foot, just behind the toes.",
      "Slowly roll the ball under the foot from toes to heel.",
      "Pause on tender spots for 5–10 seconds.",
    ],
    sportRelevance: ["run", "any"],
  },

  /* ─── Spine — lower back ─────────────────────────────────────────── */
  {
    id: "child-pose",
    name: "Child's pose",
    targetArea: "lowerBack",
    secondaryAreas: ["lats"],
    durationSec: 60,
    sides: 1,
    difficulty: "easy",
    description: "Spinal decompression. Universal calming stretch.",
    steps: [
      "Kneel with big toes touching, knees wide.",
      "Sit your hips back onto your heels.",
      "Walk your hands forward, lowering your chest toward the floor.",
      "Rest your forehead down and breathe slowly.",
    ],
    sportRelevance: ["ride", "run", "swim", "any"],
  },
  {
    id: "cat-cow",
    name: "Cat-cow",
    targetArea: "lowerBack",
    secondaryAreas: ["upperBack"],
    durationSec: 60,
    sides: 1,
    difficulty: "easy",
    description: "Spinal mobility — works the whole back, not a static hold.",
    steps: [
      "Start on hands and knees, wrists under shoulders.",
      "Inhale: drop the belly, lift chest and tailbone (cow).",
      "Exhale: round the spine, tuck the chin and tailbone (cat).",
      "Move slowly with breath for 8–10 cycles.",
    ],
    sportRelevance: ["ride", "run", "any"],
  },
  {
    id: "cobra-prone",
    name: "Low cobra",
    targetArea: "lowerBack",
    durationSec: 30,
    sides: 1,
    difficulty: "easy",
    description: "Gentle back-bend after long time in flexed cycling posture.",
    steps: [
      "Lie face down, palms flat on the floor under your shoulders.",
      "Press the tops of your feet into the floor.",
      "Lift the chest using your back muscles, only a small amount.",
      "Keep your shoulders away from the ears.",
    ],
    cautions: ["Stop if it pinches the lower back."],
    sportRelevance: ["ride", "any"],
  },

  /* ─── Spine — upper back / lats ──────────────────────────────────── */
  {
    id: "thread-the-needle",
    name: "Thread-the-needle",
    targetArea: "upperBack",
    durationSec: 45,
    sides: 2,
    difficulty: "easy",
    description: "Thoracic rotation — opens the mid-back after long hours hunched over.",
    steps: [
      "Start on hands and knees.",
      "Slide one arm under and across your body, palm up.",
      "Lower the same shoulder and ear gently toward the floor.",
      "Press the other hand into the floor to deepen.",
    ],
    sportRelevance: ["ride", "swim", "any"],
  },
  {
    id: "doorway-lat",
    name: "Doorway lat hang",
    targetArea: "lats",
    secondaryAreas: ["shoulders"],
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Side bend with arm fixed — opens the lat from shoulder to hip.",
    steps: [
      "Stand sideways near a doorframe.",
      "Reach the outer arm overhead and grab the doorframe.",
      "Let your hip sink away from your arm.",
      "Breathe into the side body.",
    ],
    sportRelevance: ["swim", "ride", "any"],
  },

  /* ─── Upper body — chest / shoulders / neck ──────────────────────── */
  {
    id: "doorway-pec",
    name: "Doorway pec stretch",
    targetArea: "chest",
    secondaryAreas: ["shoulders"],
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Counter to the hunched-over cycling and desk posture.",
    steps: [
      "Stand in a doorway. Place one forearm flat on the frame, elbow at 90°.",
      "Step the same-side foot forward through the doorway.",
      "Rotate the chest away from the planted arm.",
      "Feel the stretch across the front of the chest and shoulder.",
    ],
    sportRelevance: ["ride", "swim", "any"],
  },
  {
    id: "cross-body-shoulder",
    name: "Cross-body shoulder",
    targetArea: "shoulders",
    durationSec: 30,
    sides: 2,
    difficulty: "easy",
    description: "Classic posterior deltoid stretch.",
    steps: [
      "Stand or sit tall.",
      "Bring one arm straight across the body at shoulder height.",
      "Use the other hand to gently pull the arm closer.",
      "Keep both shoulders pulled down, away from the ears.",
    ],
    sportRelevance: ["swim", "ride", "any"],
  },
  {
    id: "sleeper-stretch",
    name: "Sleeper stretch",
    targetArea: "shoulders",
    durationSec: 30,
    sides: 2,
    difficulty: "moderate",
    description: "Restores shoulder internal rotation — key for swimmers.",
    steps: [
      "Lie on the side you want to stretch, knees bent for stability.",
      "Bend the underneath arm at 90°, palm facing up.",
      "With the top hand, gently press the forearm toward the floor.",
      "Stop at the first stretch sensation — don't force it.",
    ],
    cautions: ["Skip with a current rotator-cuff injury."],
    sportRelevance: ["swim", "any"],
  },
  {
    id: "neck-tilt",
    name: "Side-tilt neck stretch",
    targetArea: "neck",
    durationSec: 20,
    sides: 2,
    difficulty: "easy",
    description: "For the upper-trap tightness that follows long rides in the drops.",
    steps: [
      "Sit or stand tall.",
      "Drop one ear toward the same-side shoulder — gently.",
      "Place that hand on the opposite side of your head for a touch of weight (no pulling).",
      "Anchor the opposite shoulder down for a deeper stretch.",
    ],
    sportRelevance: ["ride", "swim", "any"],
  },
];

/** O(1) lookup by id. */
export const STRETCHES_BY_ID: Record<string, Stretch> = Object.fromEntries(
  STRETCHES.map((s) => [s.id, s]),
);
